dist: xenial

before_install:
  - sudo apt-get update -qq
  - uname -a

install:  
  # mecab
  - wget --no-check-certificate https://github.com/buruzaemon/natto-py/raw/master/etc/mecab-0.996.tar.gz && tar zxf mecab-0.996.tar.gz
  - pushd mecab-0.996 && ./configure --enable-utf8-only && make && sudo make install && popd
  - sudo ldconfig
  # mecab-ipadic
  - wget --no-check-certificate https://github.com/buruzaemon/natto-py/raw/master/etc/mecab-ipadic-2.7.0-20070801.tar.gz && tar zxf mecab-ipadic-2.7.0-20070801.tar.gz
  - pushd mecab-ipadic-2.7.0-20070801 && ./configure --with-charset=utf8 && make && sudo make install && popd
  - sudo ldconfig
  # mecab-jumandic
  - wget --no-check-certificate https://github.com/buruzaemon/natto-py/raw/master/etc/mecab-jumandic-7.0-20130310.tar.gz && tar zxf mecab-jumandic-7.0-20130310.tar.gz 
  - pushd mecab-jumandic-7.0-20130310 && ./configure --with-charset=utf8 && make && sudo make install && popd
  - sudo ldconfig
    # unidic-mecab
  - wget --no-check-certificate https://github.com/buruzaemon/natto-py/raw/master/etc/unidic-mecab-2.1.2_src.zip.a && wget --no-check-certificate https://github.com/buruzaemon/natto-py/raw/master/etc/unidic-mecab-2.1.2_src.zip.b && cat unidic-mecab-2.1.2_src.zip.a unidic-mecab-2.1.2_src.zip.b > unidic-mecab-2.1.2_src.zip && unzip unidic-mecab-2.1.2_src.zip 
  - pushd unidic-mecab-2.1.2_src && ./configure && make && sudo make install && popd
  - sudo ldconfig
  - "pip install cffi"
  - "pip install PyYAML>=4.2b1"
  - export MECAB_PATH=/usr/local/lib/libmecab.so
  - export MECAB_CHARSET=utf8

language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

# command to run tests
script:
  - "python setup.py test"
