before_install:
  - sudo apt-get update -qq
  - uname -a

install:  
  # mecab
  - wget --no-check-certificate https://mecab.googlecode.com/files/mecab-0.996.tar.gz && tar zxf mecab-0.996.tar.gz
  - pushd mecab-0.996 && ./configure --enable-utf8-only && make && sudo make install && popd
  - sudo ldconfig
  # mecab-ipadic
  - wget --no-check-certificate https://mecab.googlecode.com/files/mecab-ipadic-2.7.0-20070801.tar.gz && tar zxf mecab-ipadic-2.7.0-20070801.tar.gz
  - pushd mecab-ipadic-2.7.0-20070801 && ./configure --with-charset=utf8 && make && sudo make install && popd
  - sudo ldconfig
  - "pip install cffi"

language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

# command to run tests
script: test
