before_install:
  - sudo apt-get update -qq
  - uname -a

install:  
  # mecab
  - wget --no-check-certificate https://github.com/buruzaemon/natto-py/raw/master/etc/mecab-0.996.tar.gz && tar zxf mecab-0.996.tar.gz
  - pushd mecab-0.996 && ./configure --enable-utf8-only && make && sudo make install && popd
  - sudo ldconfig
  # mecab-ipadic
  - wget --no-check-certificate https://github.com/buruzaemon/natto-py/raw/master/etc/mecab-ipadic-2.7.0-20070801.tar.gz && tar zxf mecab-ipadic-2.7.0-20070801.tar.gz
  - pushd mecab-ipadic-2.7.0-20070801 && ./configure --with-charset=utf8 && make && sudo make install && popd
  - sudo ldconfig
  - "pip install cffi"
  - "pip install PyYAML"
  - export MECAB_PATH=/usr/local/lib/libmecab.so
  - export MECAB_CHARSET=utf8

language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

# command to run tests
script: "python setup.py test"
