name: learn-github-actions
on: [push]
jobs:
  test-py-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7.x' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }} 
          architecture: x64
      - run: python -V
