name: learn-github-actions
on: [push]
jobs:
  test-py-version:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
        python-version:
          - '3.5.x'
    steps:
      - uses: actions/checkout@v3
      - name: Install MeCab, etc. on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          wget --no-check-certificate https://github.com/buruzaemon/natto-py/raw/master/etc/mecab-0.996.tar.gz && tar zxf mecab-0.996.tar.gz
          pushd mecab-0.996 && ./configure --enable-utf8-only && make && sudo make install && popd
          sudo ldconfig
          wget --no-check-certificate https://github.com/buruzaemon/natto-py/raw/master/etc/mecab-ipadic-2.7.0-20070801.tar.gz && tar zxf mecab-ipadic-2.7.0-20070801.tar.gz
          pushd mecab-ipadic-2.7.0-20070801 && ./configure --with-charset=utf8 && make && sudo make install && popd
          sudo ldconfig
          wget --no-check-certificate https://github.com/buruzaemon/natto-py/raw/master/etc/mecab-jumandic-7.0-20130310.tar.gz && tar zxf mecab-jumandic-7.0-20130310.tar.gz
          pushd mecab-jumandic-7.0-20130310 && ./configure --with-charset=utf8 && make && sudo make install && popd
          sudo ldconfig
          wget --no-check-certificate https://github.com/buruzaemon/natto-py/raw/master/etc/unidic-mecab-2.1.2_src.zip.a && wget --no-check-certificate https://github.com/buruzaemon/natto-py/raw/master/etc/unidic-mecab-2.1.2_src.zip.b && cat unidic-mecab-2.1.2_src.zip.a unidic-mecab-2.1.2_src.zip.b > unidic-mecab-2.1.2_src.zip && unzip unidic-mecab-2.1.2_src.zip 
          pushd unidic-mecab-2.1.2_src && ./configure && make && sudo make install && popd
          sudo ldconfig
          sudo apt-get update && sudo apt-get install -y libyaml-dev

      - name: Install MeCab, etc. on MacOS
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install mecab
          brew install mecab-ipadic
          brew install mecab-jumandic
          brew install mecab-unidic
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }} 
          architecture: x64
      - name: pip stuff
        run: |
            pip install PyYAML>=5.4
            pip install cffi
      - name: Test
        run: python setup.py test
        env:
          MECAB_PATH: /usr/local/lib/libmecab.so                
          MECAB_CHARSET: utf8          
        
