name: learn-github-actions
on: [push]
jobs:
  test-py-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          architecture: x64
      - run: python -V
